options:
  platform:     psx
  basename:     stlib
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/LIB/LIB.BIN
  asm_path:     asm/us/st/lib
  asset_path:   assets/st/lib
  src_path:     src/st/lib
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stlib.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stlib.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stlib.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stlib
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, rodata]
      - [0xB60, rodata]
      - [0xDC0, rodata]
      - [0xDD0, rodata]
      - [0xDE0, rodata]
      - [0xDF0, rodata]
      - [0xE90, rodata]
      - [0x12C0, rodata]
      - [0x12D0, rodata]
      - [0x29F0, rodata]
      - [0x2BC0, rodata]
      - [0x2BD0, rodata]
      - [0x31F0, rodata]
      - [0x36F0, rodata]
      - [0x3880, rodata]
      - [0x3A10, rodata]
      - [0x3F60, rodata]
      - [0x1E070, rodata]
      - [0x1E670, rodata]
      - [0x22680, rodata]
      - [0x26690, rodata]
      - [0x26770, rodata]
      - [0x26950, rodata]
      - [0x26A20, rodata]
      - [0x26A90, rodata]
      - [0x26B70, rodata]
      - [0x26D50, rodata]
      - [0x26DE0, rodata]
      - [0x26E70, rodata]
      - [0x27080, rodata]
      - [0x27110, rodata]
      - [0x271A0, rodata]
      - [0x27230, rodata]
      - [0x27600, rodata]
      - [0x27690, rodata]
      - [0x27740, rodata]
      - [0x277B0, rodata]
      - [0x27830, rodata]
      - [0x278A0, rodata]
      - [0x27930, rodata]
      - [0x279C0, rodata]
      - [0x27A50, rodata]
      - [0x27C00, rodata]
      - [0x28410, rodata]
      - [0x28480, rodata]
      - [0x284F0, rodata]
      - [0x28650, rodata]
      - [0x286C0, rodata]
      - [0x28730, rodata]
      - [0x287A0, rodata]
      - [0x28810, rodata]
      - [0x28880, rodata]
      - [0x297C0, rodata]
      - [0x29830, rodata]
      - [0x298B0, rodata]
      - [0x29930, rodata]
      - [0x299A0, rodata]
      - [0x29C00, rodata]
      - [0x29C70, rodata]
      - [0x29CE0, rodata]
      - [0x29D50, rodata]
      - [0x29DC0, rodata]
      - [0x29E30, rodata]
      - [0x29EA0, rodata]
      - [0x29F10, rodata]
      - [0x29F80, rodata]
      - [0x2A080, rodata]
      - [0x2A1B0, rodata]
      - [0x2A220, rodata]
      - [0x2A290, rodata]
      - [0x2A300, rodata]
      - [0x2A370, rodata]
      - [0x2A640, rodata]
      - [0x2A6B0, rodata]
      - [0x2A720, rodata]
      - [0x2A9F0, rodata]
      - [0x2AA70, rodata]
      - [0x2ABD0, rodata]
      - [0x2AC40, rodata]
      - [0x2ADE0, rodata]
      - [0x2AF30, rodata]
      - [0x2B070, rodata]
      - [0x2B0E0, rodata]
      - [0x2B460, rodata]
      - [0x2B4D0, rodata]
      - [0x2B540, rodata]
      - [0x2B5E0, rodata]
      - [0x2B650, rodata]
      - [0x2B900, rodata]
      - [0x2BA60, rodata]
      - [0x2BA90, rodata]
      - [0x2BB40, rodata]
      - [0x2BBF0, rodata]
      - [0x2BC90, rodata]
      - [0x2C2E0, rodata]
      - [0x2C400, rodata]
      - [0x2C4F0, rodata]
      - [0x2C630, rodata]
      - [0x2C8A0, rodata]
      - [0x2C9A0, rodata]
      - [0x2CCF0, rodata]
      - [0x2D350, rodata]
      - [0x2D4F0, rodata]
      - [0x2DED0, c]
      - [0x52CE0, data]
  - [0x552CC]